name: Deploy Storybook

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar todas as dependências do monorepo
        run: npm install

      - name: Build completo com Turbo
        run: npm run build

      - name: Build do Storybook
        working-directory: packages/docs
        run: npm run build-storybook

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: packages/docs/storybook-static
          clean: true